class Solution:
    def intToRoman(self, n: int) -> str:
        roman_numeral = ""
        while n >= 1000:
            roman_numeral += "M"
            n -= 1000
        if n >= 900:
            roman_numeral += "CM"
            n -= 900
        if n >= 500:
            roman_numeral += "D"
            n -= 500
        if n >= 400:
            roman_numeral += "CD"
            n -= 400
        while n >= 100:
            roman_numeral += "C"
            n -= 100
        if n >= 90:
            roman_numeral += "XC"
            n -= 90
        if n >= 50:
            roman_numeral += "L"
            n -= 50
        if n >= 40:
            roman_numeral += "XL"
            n -= 40
        while n >= 10:
            roman_numeral += "X"
            n -= 10
        if n >= 9:
            roman_numeral += "IX"
            n -= 9
        if n >= 5:
            roman_numeral += "V"
            n -= 5
        if n >= 4:
            roman_numeral += "IV"
            n -= 4
        while n >= 1:
            roman_numeral += "I"
            n -= 1
        return roman_numeral